import Head from "next/head";
import Link from "next/link";

export default function ForgotPassword() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {/*begin::Theme mode setup on page load*/}
          {/*end::Theme mode setup on page load*/}
          {/*Begin::Google Tag Manager (noscript) */}
          {/*End::Google Tag Manager (noscript) */}
          {/*begin::Main*/}
          {/*begin::Root*/}
          <div className="d-flex flex-column flex-root">
            {/*begin::Authentication - Sign-in */}
            <div className="d-flex flex-column flex-lg-row flex-column-fluid">
              {/*begin::Logo*/}
              <a
                href="/metronic8/demo9/../demo9/index.html"
                className="d-block d-lg-none mx-auto py-20"
              >
                <img
                  alt="Logo"
                  src="default.svg"
                  className="theme-light-show h-25px"
                />
                <img
                  alt="Logo"
                  src="default-dark.svg"
                  className="theme-dark-show h-25px"
                />
              </a>
              {/*end::Logo*/}
              {/*begin::Aside*/}
              <div className="d-flex flex-column flex-column-fluid flex-center w-lg-50 p-10">
                {/*begin::Wrapper*/}
                <div className="d-flex justify-content-between flex-column-fluid flex-column w-100 mw-450px">
                  {/*begin::Header*/}
                  <div className="d-flex flex-stack py-2">
                    {/*begin::Back link*/}
                    <div className="me-2"></div>
                    {/*end::Back link*/}
                    {/*begin::Sign Up link*/}
                    <div className="m-0">
                      <span
                        className="text-gray-400 fw-bold fs-5 me-2"
                        data-kt-translate="sign-in-head-desc"
                      >
                        Not a Member yet?
                      </span>
                      <Link
                        href="/register"
                        className="link-primary fw-bold fs-5"
                      >
                        Sign Up
                      </Link>
                      {/* <a
                        href="/metronic8/demo9/../demo9/authentication/layouts/fancy/sign-up.html"
                        className="link-primary fw-bold fs-5"
                        data-kt-translate="sign-in-head-link"
                      >
                        Sign Up
                      </a> */}
                    </div>
                    {/*end::Sign Up link-*/}
                  </div>
                  {/*end::Header*/}
                  {/*begin::Body*/}
                  <div className="py-20">
                    {/*begin::Form*/}
                    <form
                      className="form w-100"
                      noValidate="novalidate"
                      id="kt_password_reset_form"
                      data-kt-redirect-url="/metronic8/demo9/../demo9/authentication/layouts/fancy/new-password.html"
                      action="#"
                    >
                      {/*begin::Heading*/}
                      <div className="text-start mb-10">
                        {/*begin::Title*/}
                        <h1
                          className="text-dark mb-3 fs-3x"
                          data-kt-translate="password-reset-title"
                        >
                          Forgot Password ?
                        </h1>
                        {/*end::Title*/}
                        {/*begin::Text*/}
                        <div
                          className="text-gray-400 fw-semibold fs-6"
                          data-kt-translate="password-reset-desc"
                        >
                          Enter your email to reset your password.
                        </div>
                        {/*end::Link*/}
                      </div>
                      {/*begin::Heading*/}
                      {/*begin::Input group*/}
                      <div className="fv-row mb-10">
                        <input
                          className="form-control form-control-solid"
                          type="email"
                          placeholder="Email"
                          name="email"
                          autoComplete="off"
                          data-kt-translate="password-reset-input-email"
                        />
                      </div>
                      {/*end::Input group*/}
                      {/*begin::Actions*/}
                      <div className="d-flex flex-stack">
                        {/*begin::Link*/}
                        <div className="m-0">
                          <Link href="/" style={{ color: "blanchedalmond" }}>
                            <button
                              id="kt_password_reset_submit"
                              className="btn btn-primary me-2"
                              data-kt-translate="password-reset-submit"
                            >
                              {/*begin::Indicator label*/}
                              <span className="indicator-label">Submit</span>
                              {/*end::Indicator label*/}
                              {/*begin::Indicator progress*/}
                              <span className="indicator-progress">
                                Please wait...{" "}
                                <span className="spinner-border spinner-border-sm align-middle ms-2" />
                              </span>
                              {/*end::Indicator progress*/}{" "}
                            </button>
                          </Link>
                          <Link
                            href="/"
                            className="btn btn-lg btn-light-primary fw-bold"
                          >
                            Cancel
                          </Link>
                          {/* <a
                            href="/metronic8/demo9/../demo9/authentication/layouts/fancy/sign-in.html"
                            className="btn btn-lg btn-light-primary fw-bold"
                            data-kt-translate="password-reset-cancel"
                          >
                            Cancel
                          </a> */}
                        </div>
                        {/*end::Link*/}
                      </div>
                      {/*end::Actions*/}
                    </form>
                  </div>
                  {/*end::Body*/}
                  {/*begin::Footer*/}
                  <div className="m-0">
                    {/*begin::Toggle*/}
                    <button
                      className="btn btn-flex btn-link rotate"
                      data-kt-menu-trigger="click"
                      data-kt-menu-placement="bottom-start"
                      data-kt-menu-offset="0px, 0px"
                    >
                      <img
                        data-kt-element="current-lang-flag"
                        className="w-25px h-25px rounded-circle me-3"
                        src="united-states.svg"
                        alt=""
                      />
                      <span
                        data-kt-element="current-lang-name"
                        className="me-2"
                      >
                        English
                      </span>
                      {/*begin::Svg Icon | path: icons/duotune/arrows/arr072.svg*/}
                      <span className="svg-icon svg-icon-3 svg-icon-muted rotate-180 m-0">
                        <svg
                          width={24}
                          height={24}
                          viewBox="0 0 24 24"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M11.4343 12.7344L7.25 8.55005C6.83579 8.13583 6.16421 8.13584 5.75 8.55005C5.33579 8.96426 5.33579 9.63583 5.75 10.05L11.2929 15.5929C11.6834 15.9835 12.3166 15.9835 12.7071 15.5929L18.25 10.05C18.6642 9.63584 18.6642 8.96426 18.25 8.55005C17.8358 8.13584 17.1642 8.13584 16.75 8.55005L12.5657 12.7344C12.2533 13.0468 11.7467 13.0468 11.4343 12.7344Z"
                            fill="currentColor"
                          />
                        </svg>
                      </span>
                      {/*end::Svg Icon*/}{" "}
                    </button>
                    {/*end::Toggle*/}
                    {/*begin::Menu*/}
                    <div
                      className="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg-light-primary fw-semibold w-200px py-4"
                      data-kt-menu="true"
                      id="kt_auth_lang_menu"
                    >
                      {/*begin::Menu item*/}
                      <div className="menu-item px-3">
                        <a
                          href="#"
                          className="menu-link d-flex px-5"
                          data-kt-lang="English"
                        >
                          <span className="symbol symbol-20px me-4">
                            <img
                              data-kt-element="lang-flag"
                              className="rounded-1"
                              src="united-states.svg"
                              alt=""
                            />
                          </span>
                          <span data-kt-element="lang-name">English</span>
                        </a>
                      </div>
                      {/*end::Menu item*/}
                      {/*begin::Menu item*/}
                      <div className="menu-item px-3">
                        <a
                          href="#"
                          className="menu-link d-flex px-5"
                          data-kt-lang="Spanish"
                        >
                          <span className="symbol symbol-20px me-4">
                            <img
                              data-kt-element="lang-flag"
                              className="rounded-1"
                              src="spain.svg"
                              alt=""
                            />
                          </span>
                          <span data-kt-element="lang-name">Spanish</span>
                        </a>
                      </div>
                      {/*end::Menu item*/}
                      {/*begin::Menu item*/}
                      <div className="menu-item px-3">
                        <a
                          href="#"
                          className="menu-link d-flex px-5"
                          data-kt-lang="German"
                        >
                          <span className="symbol symbol-20px me-4">
                            <img
                              data-kt-element="lang-flag"
                              className="rounded-1"
                              src="germany.svg"
                              alt=""
                            />
                          </span>
                          <span data-kt-element="lang-name">German</span>
                        </a>
                      </div>
                      {/*end::Menu item*/}
                      {/*begin::Menu item*/}
                      <div className="menu-item px-3">
                        <a
                          href="#"
                          className="menu-link d-flex px-5"
                          data-kt-lang="Japanese"
                        >
                          <span className="symbol symbol-20px me-4">
                            <img
                              data-kt-element="lang-flag"
                              className="rounded-1"
                              src="japan.svg"
                              alt=""
                            />
                          </span>
                          <span data-kt-element="lang-name">Japanese</span>
                        </a>
                      </div>
                      {/*end::Menu item*/}
                      {/*begin::Menu item*/}
                      <div className="menu-item px-3">
                        <a
                          href="#"
                          className="menu-link d-flex px-5"
                          data-kt-lang="French"
                        >
                          <span className="symbol symbol-20px me-4">
                            <img
                              data-kt-element="lang-flag"
                              className="rounded-1"
                              src="france.svg"
                              alt=""
                            />
                          </span>
                          <span data-kt-element="lang-name">French</span>
                        </a>
                      </div>
                      {/*end::Menu item*/}
                    </div>
                    {/*end::Menu*/}
                  </div>
                  {/*end::Footer*/}
                </div>
                {/*end::Wrapper*/}
              </div>
              {/*end::Aside*/}
              {/*begin::Body*/}
              <div
                className="d-none d-lg-flex flex-lg-row-fluid w-50 bgi-size-cover bgi-position-y-center bgi-position-x-start bgi-no-repeat"
                style={{ backgroundImage: "url(bg11.png)" }}
              ></div>
              {/*begin::Body*/}
            </div>
            {/*end::Authentication - Sign-in*/}{" "}
          </div>
          {/*end::Root*/}
          {/*end::Main*/}
          {/*begin::Javascript*/}
          {/*begin::Global Javascript Bundle(mandatory for all pages)*/}
          {/*end::Global Javascript Bundle*/}
          {/*begin::Custom Javascript(used for this page only)*/}
          {/*end::Custom Javascript*/}
          {/*end::Javascript*/}
          {/* <svg
            id="SvgjsSvg1001"
            width={2}
            height={0}
            xmlns="http://www.w3.org/2000/svg"
            version="1.1"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            xmlns:svgjs="http://svgjs.dev"
            style={{
              overflow: "hidden",
              top: "-100%",
              left: "-100%",
              position: "absolute",
              opacity: 0,
            }}
          >
            <defs id="SvgjsDefs1002" />
            <polyline id="SvgjsPolyline1003" points="0,0" />
            <path id="SvgjsPath1004" d="M0 0 " />
          </svg> */}
        </div>
      </main>
    </>
  );
}
